"""Human-readable renderings: markdown report and SVG status badge."""

from __future__ import annotations

from .models import AuditReport, Severity
from .scoring import VERDICT_AT_RISK, VERDICT_READY, VERDICT_WILL_FAIL

_SEVERITY_ICON = {
    Severity.PASS: "✅",
    Severity.INFO: "ℹ️",
    Severity.WARN: "⚠️",
    Severity.FAIL: "❌",
    Severity.CRITICAL: "🛑",
}

_VERDICT_COLOR = {
    VERDICT_READY: "#2ea44f",
    VERDICT_AT_RISK: "#d29922",
    VERDICT_WILL_FAIL: "#cf222e",
}


def report_markdown(report: AuditReport) -> str:
    lines = [
        f"# Preflight audit — {report.target_url}",
        "",
        f"**Verdict:** {report.verdict} · **Grade:** {report.grade} ({report.score}/100) · "
        f"**Kind:** {report.endpoint_kind} · **Checked:** {report.checked_at.isoformat()}",
        "",
        report.summary,
        "",
    ]
    if report.latency:
        lines += [
            f"**Latency:** median {report.latency.median_ms:.0f} ms, max {report.latency.max_ms:.0f} ms "
            f"({len(report.latency.samples_ms)} samples)",
            "",
        ]
    if report.fixes:
        lines.append("## Fix first")
        lines.extend(f"{i}. {fix}" for i, fix in enumerate(report.fixes, 1))
        lines.append("")
    lines.append("## All findings")
    lines.append("")
    lines.append("| | Check | Category | Result |")
    lines.append("|---|---|---|---|")
    order = [Severity.CRITICAL, Severity.FAIL, Severity.WARN, Severity.INFO, Severity.PASS]
    for severity in order:
        for finding in report.findings:
            if finding.severity is severity:
                detail = f" — {finding.detail}" if finding.detail else ""
                lines.append(
                    f"| {_SEVERITY_ICON[severity]} | `{finding.check_id}` | {finding.category.value} "
                    f"| **{finding.title}**{detail} |"
                )
    lines.append("")
    lines.append("_Generated by Preflight — deterministic conformance auditing for agent services._")
    return "\n".join(lines)


def badge_svg(report: AuditReport) -> str:
    color = _VERDICT_COLOR.get(report.verdict, "#57606a")
    status_text = f"{report.grade} · {report.verdict}"
    label = "preflight"
    label_width = 62
    status_width = 12 + 7 * len(status_text)
    total = label_width + status_width
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{total}" height="20" role="img" aria-label="{label}: {status_text}">
  <linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>
  <rect rx="3" width="{total}" height="20" fill="#555"/>
  <rect rx="3" x="{label_width}" width="{status_width}" height="20" fill="{color}"/>
  <rect rx="3" width="{total}" height="20" fill="url(#s)"/>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="{label_width / 2}" y="14">{label}</text>
    <text x="{label_width + status_width / 2}" y="14">{status_text}</text>
  </g>
</svg>"""
